name: WasteX Daily ETL

on:
  schedule:
    - cron: "0 17 * * *"   # 00:00 WIB
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pipeline
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: python main.py